/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { IMResourcesCategory } from "./type";

export const MResourcesCateogry = ({ category }: IMResourcesCategory) => {
  return (
    <div className="h-full  overflow-hidden rounded-md border-2 border-gray-200 border-opacity-60 dark:border-gray-700">
      <Link href={`/resources/${category._id}`}>
        <img
          alt="Midjourney Daily Theme Record"
          src="/cards/midjourney-daily-theme.jpg"
          className="object-cover object-center md:h-36 lg:h-48"
          width="544"
          height="306"
        />
      </Link>
      <div className="p-6">
        <h2 className="mb-3 text-2xl font-bold leading-8 tracking-tight">
          <Link href={`/resources/${category._id}`}>{category.name}</Link>
        </h2>
        <p className="prose mb-3 max-w-none text-gray-500 dark:text-gray-400">
          Discover the comprehensive record of daily themes in Midjourney,
          documenting the topics generated by the Midjourney team in the
          #daily-theme Discord channel every day to challenge its users
        </p>
        <Link
          className="text-base font-medium leading-6 text-primary-500 hover:text-primary-600 dark:hover:text-primary-400"
          aria-label="Link to Midjourney Daily Theme Record"
          href={`/resources/${category._id}`}
        >
          Learn more →
        </Link>
      </div>
    </div>
  );
};
